export interface IConsultaCnpj {
    cnpj: string,
    identificador_matriz_filial: number,
    descricao_identificador_matriz_filial: string,
    nome_fantasia: string,
    situacao_cadastral: number,
    descricao_situacao_cadastral: string,
    data_situacao_cadastral: string,
    motivo_situacao_cadastral: number,
    descricao_motivo_situacao_cadastral: string,
    nome_cidade_no_exterior: string,
    codigo_pais: number,
    pais: string,
    data_inicio_atividade: string,
    cnae_fiscal: number,
    cnae_fiscal_descricao: string,
    descricao_tipo_de_logradouro: string,
    logradouro: string,
    numero: string,
    complemento: string,
    bairro: string,
    cep: string,
    uf: string,
    codigo_municipio: number,
    codigo_municipio_ibge: number,
    municipio: string,
    ddd_telefone_1: string,
    ddd_telefone_2: string,
    ddd_fax: string,
    situacao_especial: string,
    data_situacao_especial: string,
    opcao_pelo_simples: true,
    data_opcao_pelo_simples: string,
    data_exclusao_do_simples: string,
    opcao_pelo_mei: true,
    data_opcao_pelo_mei: string,
    data_exclusao_do_mei: string,
    razao_social: string,
    codigo_natureza_juridica: number,
    natureza_juridica: string,
    qualificacao_do_responsavel: number,
    capital_social: number,
    codigo_porte: number,
    porte: string,
    ente_federativo_responsavel: string,
    descricao_porte: string,
    qsa: [
        {
            identificador_de_socio: number,
            nome_socio: string,
            cnpj_cpf_do_socio: string,
            codigo_qualificacao_socio: number,
            qualificacao_socio: string,
            data_entrada_sociedade: string,
            codigo_pais: number,
            pais: string,
            cpf_representante_legal: string,
            nome_representante_legal: string,
            codigo_qualificacao_representante_legal: number,
            qualificacao_representante_legal: string,
            codigo_faixa_etaria: number,
            faixa_etaria: string
        }
    ],
    cnaes_secundarios: [
        {
            codigo: number,
            descricao: string
        }
    ]
}