name: Docker Image CI

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_KEY }}" | docker login -u brunobentocaina --password-stdin

      - name: Make envfile
        run: |
          cat > .env.production
          echo "NEXT_PUBLIC_URL_API=${{ secrets.URL_API }}" >> .env.production
          echo "NEXT_PUBLIC_SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}" >> .env.production
          echo "$(<.env.production)"

      - name: Build Image
        run: |
          docker build . -t brunobentocaina/open-adm-ui:$TAG

      - name: Push
        run: |
          docker push brunobentocaina/open-adm-ui:$TAG
